# Generated by Django 3.2.8 on 2021-11-03 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20211028_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
